name: lirio-experimental-framework
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cycler=0.10.0
  - dill=0.3.4
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numexpr=2.7.3
  - olefile=0.46
  - openssl=1.1.1l
  - pandas=1.3.4
  - pillow=8.4.0
  - pip=21.2.4
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.15.0
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - clang==5.0
    - cloudpickle==2.0.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - gym==0.21.0
    - h5py==3.1.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.6
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.2
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - zipp==3.6.0
